name: Get Data from API

on:
  # schedule:
  #   - cron: '30 6 * * *' # runs at 12:00 UTC everyday
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: execute py script # run main.py to get the latest data
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          AD_ACCOUNT_ID: ${{ secrets.AD_ACCOUNT_ID }}
          GOOGLE_SHEET_SECRET: ${{ secrets.GOOGLE_SHEET_SECRET }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: python main.py
